# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

AWSTemplateFormatVersion: 2010-09-09

Description: Creates a Secrets Manager secret for various environment configurations.

Resources:
  ProTODSecret:
    # Check: CKV_AWS_149: "Ensure that Secrets Manager secret is encrypted using KMS CMK"
    # checkov:skip=CKV_AWS_149:Secrets Manager uses the key alias/aws/secretsmanager. This only stores the CSRF seed.
    Type: AWS::SecretsManager::Secret
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W77
            reason: "Secrets Manager uses the key alias/aws/secretsmanager. This only stores the CSRF seed."
    Properties:
      Description: ProTOD secrets and environment variables
      Name: app/protod

  ProTODSecretPolicy:
    Type: AWS::SecretsManager::ResourcePolicy
    Properties:
      BlockPublicPolicy: true
      ResourcePolicy: {
        "Version" : "2012-10-17",
        "Statement" : [ {
          "Effect" : "Allow",
          "Principal" : {
            "AWS" : {
                      "Fn::Sub" : [
                        "arn:aws:iam::${AWS::AccountId}:role/ProTOD/${FargateEcsTaskRole}",
                        {
                          "FargateEcsTaskRole": {
                            "Fn::ImportValue" : "FargateEcsTaskRole"
                          }
                        }
                      ]
                    }
          },
          # Check: CKV_SECRET_6: "Base64 High Entropy String" #pragma: allowlist secret
          # checkov:skip=CKV_SECRET_6:False positive. Not a secret. #pragma: allowlist secret
          "Action" : "secretsmanager:GetSecretValue", # pragma: allowlist secret
          "Resource" : "*"
        } ]
      }
      SecretId: !Ref ProTODSecret

Outputs:
  ProTODSecret:
    Description: ProTODSecret
    Value: !Ref ProTODSecret
    Export:
      Name: "ProTODSecret"