# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

ARG PROTOD_BASE

FROM ${PROTOD_BASE}

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apk add --no-cache py3-pip

RUN pip install --no-cache-dir --break-system-packages --upgrade pip boto3 \
    && rm -rf /var/cache/apk/*

VOLUME /opt/protod
VOLUME /tmp

COPY ./supporting-files/generativeai.py ./supporting-files/llms.py \
     ./supporting-files/script-bedrock.sh ./supporting-files/script-all-start.sh \
     ./supporting-files/script-all-end.sh /opt/protod/
RUN chown -R protod:protod /opt/protod \
    && chmod -R 750 /opt/protod

USER protod
WORKDIR /opt/protod

ENTRYPOINT ["/opt/protod/script-bedrock.sh"]