# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

# build the base image
ARG PROTOD_BASE

FROM ${PROTOD_BASE}

RUN apk add --no-cache git nodejs npm \
    && rm -rf /var/cache/apk/*

RUN git clone https://github.com/todogroup/repolinter.git /usr/local/repolinter && \
    cd /usr/local/repolinter && \
    rm -rf node_modules package-lock.json && \
    npm --no-save install && \
    npm update -g --no-save

VOLUME /opt/protod
VOLUME /tmp

COPY ./supporting-files/repolinter-amazon-ospo-ruleset.json ./supporting-files/script-repolinter.sh \
     ./supporting-files/script-all-start.sh ./supporting-files/script-all-end.sh /opt/protod/
RUN chown -R protod:protod /opt/protod \
    && chmod -R 750 /opt/protod

USER protod
WORKDIR /opt/protod

ENTRYPOINT ["/opt/protod/script-repolinter.sh"]
