# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

ARG PROTOD_BASE

FROM ${PROTOD_BASE}

RUN apk add --no-cache clamav \
    && rm -rf /var/cache/apk/* \
    && rm -rf /var/lib/clamav/*

VOLUME /opt/protod
VOLUME /tmp

COPY ./supporting-files/script-clamav.sh ./supporting-files/script-all-start.sh \
     ./supporting-files/script-all-end.sh /opt/protod/
RUN chown -R protod:protod /opt/protod \
    && chmod -R 750 /opt/protod

USER protod
WORKDIR /opt/protod

ENTRYPOINT ["/opt/protod/script-clamav.sh"]
