# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

ARG PROTOD_BASE

FROM ${PROTOD_BASE}

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apk add --no-cache git py3-pip \
    && rm -rf /var/cache/apk/*

RUN pip install --no-cache-dir --break-system-packages --upgrade pip detect-secrets

VOLUME /opt/protod
VOLUME /tmp
COPY ./supporting-files/script-detectsecrets.sh ./supporting-files/script-all-start.sh \
     ./supporting-files/script-all-end.sh /opt/protod/
RUN chown -R protod:protod /opt/protod \
    && chmod -R 750 /opt/protod

USER protod
WORKDIR /opt/protod

ENTRYPOINT ["/opt/protod/script-detectsecrets.sh"]
